"""add_invoice_number

Revision ID: 66a2d6825e51
Revises: 7662d26bba6b
Create Date: 2026-10-07 04:01:50.023696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a2d6825e51'
down_revision: Union[str, None] = '7662d26bba6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('invoice_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_sales_invoice_number'), 'sales', ['invoice_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_invoice_number'), table_name='sales')
    op.drop_column('sales', 'invoice_number')
    # ### end Alembic commands ###
