"""Add ProductBatch

Revision ID: 6b421d35b589
Revises: 
Create Date: 2026-10-07 03:11:14.366250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b421d35b589'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_debt_payments_business_id', table_name='debt_payments')
    op.drop_index('ix_debt_payments_debt_id', table_name='debt_payments')
    op.drop_table('debt_payments')
    op.drop_index('ix_debts_business_id', table_name='debts')
    op.drop_table('debts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debts',
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('debt_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('concept', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('paid_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name='debts_business_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='debts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_debts_business_id', 'debts', ['business_id'], unique=False)
    op.create_table('debt_payments',
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('debt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name='debt_payments_business_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], name='debt_payments_debt_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='debt_payments_pkey')
    )
    op.create_index('ix_debt_payments_debt_id', 'debt_payments', ['debt_id'], unique=False)
    op.create_index('ix_debt_payments_business_id', 'debt_payments', ['business_id'], unique=False)
    # ### end Alembic commands ###
