"""Add batch_id to SaleDetail

Revision ID: 7662d26bba6b
Revises: 6b421d35b589
Create Date: 2026-10-07 03:20:14.853114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7662d26bba6b'
down_revision: Union[str, None] = '6b421d35b589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_details', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sale_details', 'product_batches', ['batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_details', type_='foreignkey')
    op.drop_column('sale_details', 'batch_id')
    # ### end Alembic commands ###
